server:
  port: 8081

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/sso


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/