spring:
  application:
    name: ticket-service

  datasource:
    url: jdbc:postgresql://ticket-service-db:5432/ticketdb
    username: ticket
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8083


feign:
  client:
    config:
      default:
        errorDecoder: com.yusssss.sso.ticketservice.core.decoders.CustomFeignErrorDecoder